### ISSUE TITLE
Assets for next version

### ISSUE THREAD

**Issue by LefterisJP** [rotki/assets#36]
- ETH2x-FLI: https://www.coingecko.com/en/coins/eth-2x-flexible-leverage-index

**Comment by isidorosp** [comment]
SACKS: https://www.coingecko.com/en/coins/sacks
RAIL: https://www.coingecko.com/en/coins/railgun

**Comment by LefterisJP** [comment]
Oh we normally do this in the normal repo but will keep this in mind. Probably need to close this issue, or at least decide where to put them.

@yabirgb just fyi also :)

**Comment by yabirgb** [comment]
Closed by rotki/rotki#3524
